/* terminal emulation support - colors */

/* empty functions at the moment */
void bg_black(void)   { }
void bg_red(void)    { }
void bg_blue(void)   { }
void color_reset(void) { }
void color_bold(void) { }
void fg_white_force_bold(void) { }
void fg_white(void) { }
void fg_magenta(void) { }
void bold_italics_white(void) { }
void italics(void) { }
void bold_italics(void) { }
void n1uro_italics(void) { }
void fg_yellow(void) { }
